# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 906cfbad89c3d5fe93645514619d4a55ef94b028eca1e85203f54c57138bd79f79ca018e8ac22db1f8e85ac1d927a18b06aff7ce28c97c53e7634648f1090f56

test:
  secret_key_base: 86745cf18f9cb605a0c8df01bbb5840cd16839ef4851254b8aa7ad60c92b02b1674e4d4edccc0f6b6648bb50417190be44e912132c00cb734f2fc772710ec3a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
